[package]
name = "haya"
version = "0.1.0"
authors = ["Edward Fitz Abucay <ffimnsr@protonmail.ch>"]
description = "An OpenID Connect 2.0 provider implemented in pure Rust"
categories = ["authentication", "oauth2", "openid"]
keywords = ["authentication", "openid", "microservice", "provider", "cli"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/ffimnsr/haya-rs"
repository = "https://github.com/ffimnsr/haya-rs"
edition = "2018"
readme = "README.md"
exclude = [".gitignore"]

[dependencies]
dotenv = "0.15"
log = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["tracing-log"] }
tracing-attributes = "0.1"
tracing-futures = "0.2"
futures = { version = "0.3", default-features = false }
futures-util = { version = "0.3", default-features = false }
hyper = { version = "0.14", features = ["full"] }
routerify = "2.1"
reqwest = { version = "0.11", features = ["json"] }
oauth2 = "4.1"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
tokio = { version = "1.8.1", features = ["rt-multi-thread", "macros", "time"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
base64 = "0.13"
josekit = "0.7"
url = { version = "2.1", features = ["serde"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
deadpool-postgres = "0.7"
tokio-postgres = { version = "0.7", features = ["with-uuid-0_8", "with-serde_json-1", "with-chrono-0_4"] }
clap = "3.0.0-beta.2"
tinytemplate = "1.2"
