[package]
name = "charon"
version = "0.1.0"
authors = ["Ed Abucay <ffimnsr@protonmail.ch>"]
description = "OpenID Connect provider implementation"
license = "MIT"
repository = ""
edition = "2018"
readme = "README.md"

[dependencies]
dotenv = "0.15.0"
log = "0.4.14"
env_logger = "0.8.4"
futures = { version = "0.3", default-features = false }
futures-util = { version = "0.3", default-features = false }
hyper = { version = "0.14", features = ["full"] }
routerify = "2.1.0"
reqwest = { version = "0.11", features = ["json"] }
oauth2 = "4.1.0"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.8.1", features = ["rt-multi-thread", "macros", "time"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
